- .github/workflows/release.yml
> remove s3 form ci

- README.md
- hack/install-terraform-provider-harvester.sh.tpl
- scripts/package
> update README and scripts

- internal/provider/volume/resource_volume_constructor.go
> Fix volume storageclass name

- README.md
- docs/index.md
- docs/resources/virtualmachine.md
- examples/provider/provider.tf
- examples/resources/harvester_virtualmachine/resource.tf
- go.mod
- go.sum
- internal/provider/virtualmachine/resource_virtualmachine.go
- internal/provider/virtualmachine/resource_virtualmachine_constructor.go
- pkg/constants/constants_virtualmachine.go
- pkg/importer/resource_virtualmachine_importer.go
> Fix PVC delete

- internal/provider/virtualmachine/resource_virtualmachine.go
> Fix volume delete

- README.md
- docs/index.md
- examples/provider/provider.tf
- internal/provider/virtualmachine/resource_virtualmachine.go
**Related issue**
https://github.com/harvester/harvester/issues/1227
> Increase vm delete timeout to 300s

- README.md
- docs/index.md
- examples/provider/provider.tf
- internal/provider/virtualmachine/resource_virtualmachine_constructor.go
currently cloudinit doesn't work due to missing disk bus
> Fix cloudinit disk bus

- README.md
- docs/index.md
- docs/resources/virtualmachine.md
- examples/provider/provider.tf
- examples/resources/harvester_virtualmachine/resource.tf
- internal/provider/virtualmachine/resource_virtualmachine_constructor.go
- internal/provider/virtualmachine/schema_virtualmachine_disk.go
- pkg/constants/constants_virtualmachine.go
- pkg/importer/resource_virtualmachine_importer.go
1. Add hot_plug field to disk
2. fix hotplug volume bus
> Add hot_plug field to disk

- go.mod
- internal/provider/clusternetwork/resource_clusternetwork_constructor.go
- internal/provider/image/resource_image_constructor.go
- internal/provider/keypair/resource_keypair_constructor.go
- internal/provider/network/resource_network_constructor.go
- internal/provider/virtualmachine/resource_virtualmachine.go
- internal/provider/virtualmachine/resource_virtualmachine_constructor.go
- internal/provider/virtualmachine/resource_virtualmachine_validator.go
- internal/provider/volume/resource_volume_constructor.go
- internal/util/constructor.go
**Related issue**
https://github.com/harvester/harvester/issues/1807
> Add validate method and check ssh keys in cloud-init

- docs/data-sources/network.md
- docs/resources/network.md
- examples/resources/harvester_network/resource.tf
- internal/provider/network/resource_network_constructor.go
- internal/provider/network/schema_network.go
- internal/provider/virtualmachine/resource_virtualmachine_validator.go
- pkg/constants/constants_network.go
- pkg/importer/resource_network_importer.go
https://github.com/harvester/harvester/issues/1883
> Add network route

- .golangci.yml
- Dockerfile.dapper
https://github.com/harvester/harvester/issues/1868
> Switch to BCI image

- docs/resources/clusternetwork.md
- examples/resources/harvester_clusternetwork/import.sh
- examples/resources/harvester_clusternetwork/resource.tf
- internal/provider/clusternetwork/resource_clusternetwork.go
https://github.com/harvester/harvester/issues/2052
> Clusternetwork import Enhancement

- docs/index.md
- examples/provider/provider.tf
> Bump version to 0.3.1

- internal/provider/virtualmachine/resource_virtualmachine_validator.go
- internal/provider/virtualmachine/resource_virtualmachine_validator_test.go
https://github.com/harvester/harvester/issues/2095
> Support ssh_authorized_keys in users

- docs/index.md
- examples/provider/provider.tf
> Bump version to 0.3.2

- docs/index.md
- examples/provider/provider.tf
> Bump version to 0.4.0

- docs/index.md
- examples/provider/provider.tf
> Bump version to 0.5.0

- go.mod
- go.sum
https://github.com/harvester/harvester/issues/2604
> Bump harvester to harvester/harvester@e155700

- docs/data-sources/virtualmachine.md
- docs/resources/virtualmachine.md
- examples/resources/harvester_virtualmachine/resource.tf
- internal/provider/virtualmachine/resource_virtualmachine_constructor.go
- internal/provider/virtualmachine/schema_virtualmachine.go
- pkg/constants/constants_virtualmachine.go
- pkg/importer/resource_virtualmachine_importer.go
issue [#2754](https://github.com/harvester/harvester/issues/2754)
> Add EFI boot and Secure Boot options support.

- internal/provider/virtualmachine/resource_virtualmachine_constructor.go
- package/Dockerfile
issue [#2754](https://github.com/harvester/harvester/issues/2754)
> Add SMM enabler for Secure Boot.

- docs/index.md
- examples/provider/provider.tf
release a new version still support harvester 1.0.3
next version will only support 1.1.0
> Bump version to v0.5.2

- internal/provider/virtualmachine/resource_virtualmachine_constructor.go
https://github.com/harvester/harvester/issues/3248
*Test plan**
- Setup test env by https://github.com/harvester/terraform-provider-harvester/wiki/Use-the-master-head-docker-image-for-testing for `Tester`
- Create a test config file
```bash
vim main.tf
```
```hcl
url          = "http://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img"
}
resource "harvester_virtualmachine" "ubuntu20" {
name                 = "ubuntu20"
namespace            = …
```
> Fix image volume storageclass error

- docs/index.md
- examples/provider/provider.tf
> Bump version to 0.6.1

- internal/provider/network/resource_network_constructor.go
Fixe update network description did not take effect found in https://github.com/harvester/terraform-provider-harvester/pull/60
> Fix update network description

- docs/index.md
- examples/provider/provider.tf
> Bump version to 0.5.4

- docs/index.md
- examples/provider/provider.tf
- package/Dockerfile
- package/provider.tf
- scripts/package
- setup-test-env.sh
- Bump terraform version to the latest 1.4.6
- Add a script setup-test-env.sh for test
try:
```bash
./setup-test-env.sh ~/.kube/config
```
> Bump terraform version and add setup-test-env.sh

- docs/index.md
- examples/provider/provider.tf
> Bump version to v0.6.3

- .github/workflows/build.yml
- Dockerfile.dapper
- package/Dockerfile
- scripts/build
- scripts/package
- scripts/version
Rely on https://github.com/rancherlabs/eio/issues/2149
Ref: https://github.com/harvester/harvester/issues/5327
> ci: add build GitHub action

- Dockerfile.dapper
- go.mod
https://github.com/harvester/harvester/issues/6160
> feat: upgrade go version to 1.22

- .github/workflows/release.yml
- .golangci.yml
- Dockerfile.dapper
- go.mod
- internal/provider/virtualmachine/resource_virtualmachine_constructor.go
https://github.com/harvester/harvester/issues/7336
> feat: bump go to v1.23

- .goreleaser.yml
Sample CI: https://github.com/FrankYang0529/terraform-provider-harvester/actions/runs/14394165125/job/40366774032
> ci: fix gorelease with --pinentry-mode loopback

- renovate.json
https://github.com/harvester/harvester/issues/8708
> feat: ignore provider.tf
