harvester/terraform-provider-harvester

- internal/provider/clusternetwork/datasource_clusternetwork.go
- internal/provider/image/datasource_image.go
- internal/provider/keypair/datasource_keypair.go
- internal/provider/network/datasource_network.go
- internal/provider/virtualmachine/datasource_virtualmachine.go
- internal/provider/volume/datasource_volume.go
For data source, if the resource cannot be found in the cluster based on the name and namespace, an error message should be reported.
otherwise, the user might use an empty id in other resources
https://github.com/harvester/harvester/issues/2461
**Test Plan**
1. create a network `vlan1` in the namespace `harvester-public` form UI side
2. create a data source harvester_network.vlan1, do not specify namespace, It will default to `default`
```hcl
data "harvester_network" "vlan1" {
name      = "vlan1"
}
```
3. terraform apply
4. users will get an error
```
Error: network-attachment-definitions.k8s.cni.cncf.io "vlan1" not found
```
6. add correct namespace to the data source
```hcl
data "harvester_network" "vlan1" {
name      = "vlan1"
}
```
7. …
> should report not found error when data source read

- package/Dockerfile
bump vim version
fix https://drone-publish.rancher.io/harvester/terraform-provider-harvester/52
> Update Dockerfile to fix ci

- docs/index.md
- internal/provider/provider.go
- pkg/client/client.go
- pkg/constants/constants.go
Add ability to pass kubernetes context in the provider.
`GetNonInteractiveClientConfig` (old) calls `GetNonInteractiveClientConfigWithContext` (new) internally with an empty context, so there's no change in behaviour there.
Renamed the constant `FiledProviderKubeConfig` as there was a typo before `Filed...` -> `Field...`
> Add ability to pass kubernetes context in the provider

- docs/index.md
- examples/provider/provider.tf
- Bump version to 0.5.3
**Release Note**
- Add ability to pass kubernetes context in the provider (https://github.com/harvester/terraform-provider-harvester/pull/55) (@vulkoingim)
> Bump version to 0.5.3

- docs/resources/image.md
- docs/resources/volume.md
- examples/resources/harvester_image/resource.tf
- examples/resources/harvester_volume/resource.tf
use harvester_image id instead of image namspace/name
to make sure that the dependencies between resources are correct
> Update image volume examples and docs

- docs/index.md
- examples/provider/provider.tf
- internal/provider/provider.go
1. storage tiering
2. vlan enhancement
- ---
Supported Harvester Versions:
- v1.1.0
------
harvester version check before plan or apply:
```bash
7e43a613aba5:/data # terraform plan
╷
│ Error: current Harvester server version is v1.0.3, the minimum supported version is v1.1.0
│
│   with provider["registry.terraform.io/harvester/harvester"],
│   on provider.tf line 9, in provider "harvester":
│    9: provider "harvester" {
│
╵
7e43a613aba5:/data # terraform apply
╷
│ Error: current Harvester server version is v1.0.3, the minimum supported version is v1.1.0
│
│   with provider["registry.terraform.io/harvester/harvester"],
│   on provider.tf line 9, in provider "harvester":
│    9: provider "harvester" {
│
╵
```
> Bump version to 0.6.0

- package/Dockerfile
**Problem**
**Solution**
use `hadolint ignore=DL3037` to skip package version validation
> Fix package version

- pkg/importer/resource_network_importer.go
https://github.com/harvester/harvester/issues/2857
**Test plan**
- Setup test env by https://github.com/harvester/terraform-provider-harvester/wiki/Use-the-master-head-docker-image-for-testing for `Tester`
- Create a test config file
```bash
vim main.tf
```
**Network**
- Add resource `harvester_network` with `route_mode = "auto"` and `route_dhcp_server_ip = "<replace to your dhcp server>"`
```hcl
resource "harvester_network" "mgmt-vlan1" {
name      = "mgmt-vlan1"
vlan_id = 1
route_mode           = "auto"
route_dhcp_server_ip = "192.168.5.1"
cluster_network_name = "mgmt"
}
```
- …
> Fix network apply error with dhcpserver

- internal/provider/network/resource_network_constructor.go
- package/Dockerfile
- pkg/importer/resource_network_importer.go
backport
https://github.com/harvester/terraform-provider-harvester/pull/60
https://github.com/harvester/terraform-provider-harvester/pull/66
https://github.com/harvester/terraform-provider-harvester/pull/68
https://github.com/harvester/harvester/issues/3284
**Test plan**
- Prepare a v1.0.3 Harvester cluster
- Enable cluster network
or Setup test env by https://github.com/harvester/terraform-provider-harvester/wiki/Use-the-prebuilt-docker-image-for-testing for `Tester` (need to change BRANCH to v1.0)
- Create a test config file
```bash
vim main.tf
```
**Network**
- Add resource `harvester_network` with `route_mode …
> [backport v1.0]Fix network apply error with dhcpserver

- docs/data-sources/virtualmachine.md
- docs/resources/virtualmachine.md
- examples/resources/harvester_virtualmachine/resource.tf
- internal/provider/virtualmachine/resource_virtualmachine_constructor.go
- internal/provider/virtualmachine/schema_virtualmachine.go
- pkg/constants/constants_virtualmachine.go
- pkg/importer/resource_virtualmachine_importer.go
https://github.com/harvester/harvester/issues/3402
* Setup test env by https://github.com/harvester/terraform-provider-harvester/wiki/PR-Test-Env-Setup for `Reviwer`
* Setup test env by https://github.com/harvester/terraform-provider-harvester/wiki/Use-the-master-head-docker-image-for-testing for `Tester`
* Create a test config file in the test container 
```
url          = "http://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img"
}
resource "harvester_virtualmachine" "ubuntu20" {
name                 = "ubuntu20"
namespace            = "default"
restart_after_update = true …
```
> Add the ability to provide reserved_memory annotation field in virtual machine

- internal/provider/virtualmachine/resource_virtualmachine_constructor.go
https://github.com/harvester/harvester/issues/3336
**Problem**
The input device cannot be removed normally
**Test plan**
1.  create a vm with an input device
```hcl
url          = "http://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img"
}
resource "harvester_virtualmachine" "ubuntu20" {
name                 = "ubuntu20"
namespace            = "default"
restart_after_update = true
description = "test ubuntu20 raw image"
tags = {
ssh-user = "ubuntu"
}
cpu    = 2
memory = "2Gi"
efi         = true
secure_boot = true
run_strategy    = "RerunOnFailure"
hostname …
```
> Fix input device update

- .gitignore
- docs/data-sources/virtualmachine.md
- docs/resources/virtualmachine.md
- internal/provider/virtualmachine/resource_virtualmachine_constructor.go
- internal/provider/virtualmachine/schema_virtualmachine.go
- internal/provider/virtualmachine/schema_virtualmachine_tpm.go
- pkg/constants/constants_virtualmachine.go
- pkg/importer/resource_virtualmachine_importer.go
https://github.com/harvester/harvester/issues/2910
**Test plan**
- Setup test env by https://github.com/harvester/terraform-provider-harvester/wiki/Use-the-master-head-docker-image-for-testing for `Tester`
**Linux**
- Create a test config file in the test container
```bash
vim linux.tf
```
```hcl
url          = "http://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img"
}
resource "harvester_virtualmachine" "tf-test" {
name                 = …
```
> Suppot TPM

- internal/provider/virtualmachine/resource_virtualmachine_validator.go
https://github.com/harvester/harvester/issues/3385
**Test plan**
- Setup test env by https://github.com/harvester/terraform-provider-harvester/wiki/Use-the-master-head-docker-image-for-testing for `Tester`
- copy id_rsa.pub to test container
```bash
docker cp ~/.ssh/id_rsa.pub tf:/data/id_rsa.pub
```
- Create a test config file in the test container
```bash
vim main.tf
```
```hcl
resource "harvester_network" "vlan1" {
name      = "vlan1"
vlan_id = 1
route_mode           = "auto"
route_dhcp_server_ip = ""
cluster_network_name = "mgmt"
}
resource "harvester_image" "ubuntu" {
name …
```
> Support sshkey from templatefile

- internal/provider/vlanconfig/schema_vlanconfig_uplink.go
While not a valid option per the Kernel's documentation, Harvester uses -1 as a special value to preserve whatever the current value is. If -1 is not allowed and the option is simply omitted for the vlanconfig, the Terraform provider will always show a change of the state from -1 to "null" at every run.
The vlanconfig cannot be changed without stopping all the VM instances using it, which is why it would be useful to allow the special value that preserves the existing configuration.
> Allow -1 value for bond_miimon uplink bond option

- .github/workflows/release.yml
Without quote, CI think 1.20 as 1.2.
Ref: https://github.com/harvester/terraform-provider-harvester/actions/runs/7296020228/job/19883228070
> ci: fix go version with quote for release

- docs/resources/network.md
- internal/provider/network/resource_network_constructor.go
- internal/provider/network/schema_network.go
- internal/tests/resource_network_test.go
issue: https://github.com/harvester/harvester/issues/5226
Setup: Create a Harvester cluster
Case 1: new terraform provider
1. Build terraform-harvester-provider.
```
CGO_ENABLED=0 go build -mod=vendor -o bin/terraform-provider-harvester .
mkdir -p ~/.terraform.d/plugins/registry.terraform.io/harvester/harvester/0.0.0-dev/linux_amd64
cp bin/terraform-provider-harvester ~/.terraform.d/plugins/registry.terraform.io/harvester/harvester/0.0.0-dev/linux_amd64/terraform-provider-harvester_v0.0.0-dev
```
2. Create a temporary folder and put the following content in `versions.tf`.
```terraform
terraform {
required_providers {
harvester = {
source  = "harvester/harvester"
/* version = "0.6.4" */
version = "0.0.0-dev"
}
}
}
provider "harvester" {
kubeconfig = "~/.kube/config"
}
```
3. Put the …
> fix: add UntaggedNetwork and remove NetworkTypeCustom 

- README.md
now we use go 1.21 instead of v1.20
> MINOR: Fix go version in readme

- internal/provider/virtualmachine/resource_virtualmachine_constructor.go
issue: https://github.com/harvester/harvester/issues/5165
1. Build terraform-harvester-provider.
```bash
CGO_ENABLED=0 go build -mod=vendor -o bin/terraform-provider-harvester .
mkdir -p ~/.terraform.d/plugins/registry.terraform.io/harvester/harvester/0.0.0-dev/linux_amd64
cp bin/terraform-provider-harvester ~/.terraform.d/plugins/registry.terraform.io/harvester/harvester/0.0.0-dev/linux_amd64/terraform-provider-harvester_v0.0.0-dev
```
2. Create a temporary folder and put the following content in `versions.tf`.
```terraform
terraform {
required_providers {
harvester = {
source  = "harvester/harvester"
/* version = "0.6.4" */
version = "0.0.0-dev"
}
}
}
provider "harvester" {
kubeconfig = "~/.kube/config"
}
```
3. Put the following content in `main.tf` in the temporary folder. …
> fix: get storage class name from vmimage status

- internal/provider/cloudinitsecret/resource_cloudinitsecret.go
- internal/provider/clusternetwork/resource_clusternetwork.go
- internal/provider/image/resource_image.go
- internal/provider/keypair/resource_keypair.go
- internal/provider/network/resource_network.go
- internal/provider/provider.go
- internal/provider/storageclass/resource_storageclass.go
- internal/provider/virtualmachine/resource_virtualmachine.go
- internal/provider/vlanconfig/resource_vlanconfig.go
- internal/provider/volume/resource_volume.go
- internal/util/state.go
- pkg/constants/constants_image.go
By convention (https://developer.hashicorp.com/terraform/language/resources/syntax#operation-timeouts) terraform resources can have timeouts associated with their operations through `timeout` blocks.
This change sets the default timeout to 2 minutes, except where other defaults were hard-coded before and allows users to specify timeout blocks without causing parsing errors.
Use the contexts to setup and propagate deadlines for each operation according to what is set in the terraform file. Since each API call happens within the same context, the same deadline applies, giving each operation (create, update, read, delete) as a whole the configured timeout rather than setting this timeout on individual API calls of the operation.
Where applicable, the timeout of resources is measured against …
> Add timeout blocks for Terraform resources

- .github/workflows/build.yml
as title, now the `Build and push images` job failed due to incorrect secrets.
> Fix github actions docker secrets

- Dockerfile.dapper
- internal/provider/network/resource_network.go
- internal/provider/network/resource_network_constructor.go
- internal/provider/volume/resource_volume.go
- internal/tests/resource_network_test.go
- internal/tests/resource_storageclass_test.go
- scripts/ci
- scripts/default
- scripts/test
Enable acceptance tests and fix existing tests and providers
1) Enable running acceptance tests on `make test` command when the user
places a kubeconfig file into the repository. This kubeconfig is
necessary since the acceptance tests are checked against a real
Harvester cluster. If the kubeconfig file is missing, only unit tests
are run, which doesn't require a Harvester cluster.
2) Fix existing tests. Some existing acceptance tests where using
invalid terraform resources. These are fixed
3) Fix volume and network resource providers. Running acceptance tests
revealed bugs in the volume and network resource providers. Both were
using an incorrect method to determine if a resource had been deleted
in Harvester. The bug was that the resource providers were waiting
for a deletion event, …
> Tests: Enable Acceptance Tests

- .github/workflows/release.yml
- .goreleaser.yml
* change actions/checkout to v4
* change actions/setup-go to v5
* change go-version to v1.22
* change goreleaser/goreleaser-action to v6
* add "version: 2" to .goreleaser.yml
* remove darwin from .goreleaser.yml, because we import
longhorn/go-common-libs which uses unix.CLONE_NEWNET
> fix: release pipeline

- internal/provider/virtualmachine/resource_virtualmachine.go
- internal/provider/virtualmachine/resource_virtualmachine_constructor.go
- internal/tests/provider_test.go
- internal/tests/resource_virtualmachine_test.go
Fix type conversion for input device blocks in virtual machine resource. Fix virtual machine resource deletion.
related-to: harvester/harvester#6647
> virtual machine resource: fix input devices

- README.md
- go.mod
- Spelling mistake in `go.mod`
- `README.md` formatting
> chore: minor changes

- Dockerfile.dapper
- internal/provider/virtualmachine/resource_virtualmachine_constructor.go
- internal/tests/resource_virtualmachine_test.go
The `harvester_virtualmachine` and its subresources are parsed and converted into a `kubevirtv1.VirtualMachine` object using a `VMBuilder` factory. This `VMBuilder` assumes that parameters given to it have some semblance of sanity. This means amongst other things that the `size` parameter of a volume must be a parseable into a `resource.Quantity` using `resource.MustParse`, e.g. `"10Gi"`.
The `size` parameter isn't always required, but when it is required, if a user omits it the Terraform provider will just fill it with a default value.
Since the `size` parameter of a `disk` subresource of a `harvester_virtualmachine` is user input, it must be sanitized before being passed on to the `VMBuilder`. In case it isn't parseable, a sensible error must be emitted and further processing of the …
> Fix: panic and crash when `size` parameter of a `disk` is not parseable into a `Quantity`

- examples/provider/provider.tf
- internal/provider/provider.go
- pkg/client/client.go
- pkg/constants/constants.go
Accept kubeconfig as base64 string.
When configuring the Harvester Terraform provider, the kubeconfig can either be given as path to a file, from which to read, or the contents can be supplied directly as base64 string.
This allows for greater flexibility in supplying this sensitive data to the Terraform provider.
related-to: harvester/harvester#6234
> Terraform Provider: Kubeconfig as Base64 string

- internal/tests/resource_volume_test.go
Add test step ensuring that volumes are deleted correctly. This test works independent of the timeout since in case the timeout is exceeded the delete operation will already be considered a fail. Thus, if the test step succeeds, the delete would not have timed out. The test step also ensures that the resource is actually removed.
The actual delete logic for volumes was already fixed in 55ee9e6 (https://github.com/harvester/terraform-provider-harvester/pull/103)
related-to: harvester/harvester#6415
> Add Volume Delete Test Step

- docs/resources/virtualmachine.md
https://github.com/harvester/harvester/issues/7503
Add a simple description for `virtualmachine.disk.image` to avoid misuse.
> doc: add virtualmachine.disk data composition description

- docs/data-sources/virtualmachine.md
- docs/resources/virtualmachine.md
- internal/provider/keypair/resource_keypair.go
- internal/provider/virtualmachine/resource_virtualmachine_constructor.go
- internal/provider/virtualmachine/schema_virtualmachine.go
- pkg/constants/constants_virtualmachine.go
https://github.com/harvester/harvester/issues/7790
Sample terraform:
```
data "harvester_image" "ubuntu20" {
name      = "focal-image"
namespace = "default"
}
resource "harvester_virtualmachine" "ubuntu20" {
name                 = "ubuntu20"
namespace            = "default"
restart_after_update = true
description = "test ubuntu20 raw image"
tags = {
ssh-user = "thisistest"
}
cpu    = 1
memory = "2Gi"
run_strategy    = "RerunOnFailure"
hostname        = "ubuntu20"
reserved_memory = "100Mi"
machine_type    = "q35"
network_interface {
name           = "nic-1"
wait_for_lease = true
}
disk {
name       = "rootdisk"
type       = "disk"
size       = "10Gi"
bus        = "virtio"
boot_order = 1
image       = data.harvester_image.ubuntu20.id
auto_delete = true
}
cloudinit {
user_data    = <<-EOF …
```
> fix(virtualmachine): ssh-user and ssh_keys

- examples/resources/harvester_ippool/resources.tf
- examples/resources/harvester_loadbalancer/resources.tf
- internal/provider/loadbalancer/resource_loadbalancer_constructor.go
- Missing Parser for the `ippool` field of the load balancer resource
- Use of incorrect in-place constants for validating the IPAM and workload type fields
- Inaccurate examples
- Implement field parser for ippool field
- Use correct constants for field validation of IPAM and workload type field
- Update examples with working code and add clarifying annotations
related-to: harvester/harvester#4814
The following terraform file should now create correct resources.
Modification to the IP ranges to fit the test environment may be necessary.
```
url          = "http://cloud-images.ubuntu.com/releases/focal/release/ubuntu …
```
> fixups for loadbalancer resource constructor

- docs/data-sources/virtualmachine.md
- docs/resources/virtualmachine.md
- internal/provider/virtualmachine/resource_virtualmachine_constructor.go
- internal/provider/virtualmachine/schema_virtualmachine.go
- pkg/constants/constants_virtualmachine.go
- pkg/importer/resource_virtualmachine_importer.go
https://github.com/harvester/harvester/issues/8705
**Build terraform-provider-harvester**
```
> rm -rf ~/.terraform.d
> CGO_ENABLED=0 go build -mod=vendor -o bin/terraform-provider-harvester .
mkdir -p ~/.terraform.d/plugins/registry.terraform.io/harvester/harvester/0.0.0-dev/linux_amd64
cp bin/terraform-provider-harvester ~/.terraform.d/plugins/registry.terraform.io/harvester/harvester/0.0.0-dev/linux_amd64/terraform-provider-harvester_v0.0.0-dev
```
**Run terraform**
1. Create `versions.tf`.
```tf
terraform {
required_providers {
harvester = {
source  = "harvester/harvester"
version = "0.0.0-dev"
}
}
}
```
2. Create `main.tf`. Assumed your node name is `harvester-node-0`.
```tf
name      = "ubuntu-focal"
namespace = "default"
display_name = …
```
> feat: add node_selector to vm

- pkg/importer/resource_network_importer.go
Import full route information into terraform state
related-to: harvester/harvester#8867
related-to: https://github.com/harvester/harvester/issues/8398#issuecomment-3166110194
Route information in Terraform state incomplete, even after running `terraform refresh`
Import full route information into Terraform state
related-to: harvester/harvester#8867
related-to: https://github.com/harvester/harvester/issues/8398#issuecomment-3166110194
- Install Harvester (any recent version)
- Create Harvester network, e.g.:
```
resource "harvester_network" "foobar" {
name = "foobar"
namespace = "default"
route_mode = "auto"
cluster_network_name = "mgmt"
vlan_id = 1
}
```
- Wait until route information is available
```
$ terraform refresh
harvester_network.foobar: Refreshing state... [id=default/foobar] …
```
> add route information to Terraform state

- .gitignore
- Dockerfile.dapper
- pkg/helper/ip.go
- pkg/helper/ip_test.go
- pkg/importer/resource_virtualmachine_importer.go
- pkg/importer/resource_virtualmachine_importer_test.go
- scripts/test
Differentiate and ignore link-local IP addresses when importing VM data.
Link-local IP addresses are IPs that the network interface itself selects when no other IP address has been given.
In case ip addresses are assigned using e.g. DHCP, the configuration of a link-local address may happen before the intended IP address is configured.
This results in wrong IP addresses being reported for VMs that are imported by the Terraform provider.
To combat this, the Terraform provider will ignore link-local IP addresses.
Additionally, the Terraform provider will always report the lexicographically lowest IP address for interfaces that have multiple IP addresses.
related-to: harvester/harvester#8900
The Terraform provider would sometimes import wrong IP addresses, particularly link-local IP …
> importer: differentiate and ignore link-local IPs
